services:
  obsidian:
    build: .
    container_name: obsidian
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./obsidian/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
